{{- if .Values.kubeconfig.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.kubeconfig.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "integr8scode.labels" . | nindent 4 }}
type: Opaque
stringData:
  kubeconfig.yaml: |
    apiVersion: v1
    kind: Config
    clusters:
    - cluster:
        {{- if .Values.kubeconfig.caCertificate }}
        certificate-authority-data: {{ .Values.kubeconfig.caCertificate }}
        {{- else }}
        # For in-cluster access, use the mounted CA
        certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        {{- end }}
        server: {{ .Values.kubeconfig.server | default "https://kubernetes.default.svc:443" }}
      name: default-cluster
    contexts:
    - context:
        cluster: default-cluster
        namespace: {{ .Release.Namespace }}
        user: default-user
      name: default-context
    current-context: default-context
    users:
    - name: default-user
      user:
        {{- if .Values.kubeconfig.token }}
        token: {{ .Values.kubeconfig.token }}
        {{- else }}
        # For in-cluster access, use the mounted service account token
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
        {{- end }}
{{- end }}
