{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "integr8scode.fullname" . }}-executor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "integr8scode.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "integr8scode.fullname" . }}-executor
subjects:
  - kind: ServiceAccount
    name: {{ include "integr8scode.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
