{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "integr8scode.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "integr8scode.labels" . | nindent 4 }}
  {{- with .Values.rbac.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
